name: psych-audio
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
      - numpy
      - pandas
      - python-dotenv
      - pydub
      - faster-whisper
      - "huggingface_hub[cli]"
      - openai
      - git+https://github.com/openai/whisper.git
      - git+https://github.com/pyannote/pyannote-audio.git
      - openai-whisper